### ISSUE TITLE
"esbuild" Peer dependency version

### ISSUE THREAD

**Issue by Nikoms** [anatine/esbuildnx#19]
Hello!

We used this plugin for our project, but It seems that the peer dependency of esbuild is very specific `"esbuild": "~0.12.17"`. We upgraded to `0.14.25` and I'm wondering if you have any idea or we could tackle this? Did you test already this plugin with the latest version of `esbuild`?

Thank you 😊

**Comment by Brian-McBride** [comment]
Published version with updated peerDependencies
```
  "peerDependencies": {
    "esbuild": "~0.14.29"
  }
```

**Comment by Nikoms** [comment]
It's when a library changed his public api and is not compatible with the previous version anymore

**Comment by Brian-McBride** [comment]
Oh. Breaking change. lol. The tests passed when I updated. This Nx plugin really just does an `esbuild` and a `tsc` compile check at the same time. I did the `tsc` so compile errors would surface. It is a shame because it makes the build seem slower as `tsc` isn't nearly as fast as `esbuild`. But it doesn't delay the output of `esbuild` itself. Also, in a large project since `tsc` is just doing the type checking, it is faster than if it were doing a full compile.
